class_name Tile

const SIZE : Vector2 = Vector2(112, 96)

enum Type {
	NONE = -1,
	FOREST = 0,
	DEAD_FOREST = 1,
	FARM = 2,
	MEADOW = 3,
	GRASS = 4,
	PATCHED_GRASS = 5,
	DIRT = 6,
	STONE = 7,
	CRACKED_STONE = 8,
	WATER = 9,
	MURKY_WATER = 10,
	LUMBERJACK = 11,
	MINE = 12,
	POWER_PLANT = 14,
	PYLON = 15,
	WOOD_REFINERY = 19,
	MINERALS_REFINERY = 20,
	LUMBER_FACTORY = 13,
	METAL_FACTORY = 16,
	MINERALS_FACTORY = 17,
	WOOD_FACTORY = 18,
}
